import React, {useState}from "react";
import { Form } from "./Form";
import { CarTable } from "./CarTable";
import { ToolHeader } from "./ToolHeader";

export const Cartool = (props) => {
    
    const initialState = {
        make:"",
        model:"",
        year: 1900,
        price: 0,
        colour: "",
    }
    
    //set state for table data
    const [cars, setCars] = useState(props.cars.concat())
    const [editCarId, setEditCarID] = useState(-1)



    const addCar = (car) => {
        setCars(
            // concatinates cars (imported list) with cardata  (form) + id, id is generated by
            // finding the largest current id accross all cars and adding 1

            cars.concat({...car,
            id: Math.max(...cars.map(c => c.id)) + 1,}),
        )
        console.log(cars)
        
    }

    const deleteCar = (id) => {
        setCars(
            //returns all cars where car.id != id is true
            cars.filter(car => car.id !== id)
        )
        setEditCarID(-1)
    }

    const replaceCar = (car) => {
        console.log("running replace car")
        const newCars = cars.concat();
        const indexToReplace = newCars.findIndex(c => c.id === car.id)
        newCars[indexToReplace] = car
        setCars(
            newCars
        )
        setEditCarID(-1)

    }

    const editCar = (id) => {
        setEditCarID(id)
    }

    const cancelCar = () => {
        setEditCarID(-1)
    }

    return(
        <>
            <ToolHeader headerText="header string"/>
            <CarTable cars={cars} editCarId={editCarId} onDeleteCar={deleteCar} onEditCar={editCar} 
            onSaveCar={replaceCar}  onCancelCar={cancelCar} 
            initialState={initialState}/>  

            <Form buttonText="add" onAddCar={addCar} initialState={initialState}/>
        </>
    )
}; 