import React, {useState}from "react";
import { Form } from "./Form";
import { CarTable } from "./TabelBody";
import { ToolHeader } from "./ToolHeader";

export const Cartool = (props) => {
    
    const initialState = {
        make:"",
        model:"",
        year: 1900,
        price: 0,
        colour: "",
    }
    
    //set state for table data
    const [cars, setCars] = useState(
        props.cars.concat()
        )



    const addCar = (car) => {
        setCars(
            // concatinates cars (imported list) with cardata  (form) + id, id is generated by
            // finding the largest current id accross all cars and adding 1

            cars.concat({...car,
            id: Math.max(...cars.map(c => c.id)) + 1,}),
        )
        console.log(cars)
        
    }

    const deleteCar = (id) => {
        setCars(
            //returns all cars where car.id != id is true
            cars.filter(car => car.id !== id)
        )
    }

    return(
        <>
            <ToolHeader headerText="header string"/>
            <CarTable cars={cars} onDeleteCar={deleteCar}/>  
            <Form buttonText="add" addCar={addCar} initialState={initialState}/>
        </>
    )
    
    
}; 